name: yalkey_0206_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+3
  flutter_local_notifications: ^9.2.0
  timezone: ^0.8.0
  path_provider: ^2.0.2
  url_launcher: ^6.0.0
  flutter_link_previewer: ^3.2.2
  provider: ^6.1.2
  persistent_bottom_nav_bar: ^5.0.2
  connectivity_plus: ^5.0.2
  badges: ^3.1.2
  fl_chart: ^0.66.2
  table_calendar: ^3.0.9
  flutter_downloader: ^1.11.6
  flutter_file_dialog: ^3.0.2
  dio: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  image_cropper: ^1.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/yalkey_icon_ios.png"
  adaptive_icon_background: "#ae0103"
  adaptive_icon_foreground: "assets/images/yalkey_icon_android.png"
  remove_alpha_ios: true